name = "symmetry-api"
main = "worker.js"
compatibility_date = "2024-01-01"

[vars]
ALLOWED_ORIGIN = "https://symmetry.salmonholic.com"
ADBC_TOKEN = "df26c13a4b613cb4aaa0d86ef9662ca0"

[triggers]
crons = ["* * * * *"]

[[kv_namespaces]]
binding = "ITEMS_KV"
id = "4d5915ca086341d982a00ed137633f80"

[[kv_namespaces]]
binding = "CPQ_KV"
id = "96edcd46f8ed471693b63783e4de9936"
